// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using maERP.Persistence.DatabaseContext;

#nullable disable

namespace maERP.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240511180250_extendModels2")]
    partial class extendModels2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("maERP.Domain.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "DE",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2623),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2626),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "AT",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2629),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2630),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "CH",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2631),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2631),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "AD",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2632),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2633),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "AF",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2634),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2634),
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 6,
                            CountryCode = "AG",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2636),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2636),
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            CountryCode = "AL",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2637),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2638),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 8,
                            CountryCode = "AM",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2639),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2639),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            CountryCode = "AO",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2640),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2641),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 10,
                            CountryCode = "AX",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2642),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2642),
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 11,
                            CountryCode = "AR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2643),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2644),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            CountryCode = "AT",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2645),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2645),
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 13,
                            CountryCode = "AU",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2646),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2647),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 14,
                            CountryCode = "AZ",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2648),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2648),
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 15,
                            CountryCode = "BA",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2649),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2650),
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 16,
                            CountryCode = "BB",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2651),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2652),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 17,
                            CountryCode = "BE",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2653),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2653),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            CountryCode = "BG",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2654),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2655),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 19,
                            CountryCode = "BL",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2656),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2656),
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 20,
                            CountryCode = "BO",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2657),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2658),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 21,
                            CountryCode = "BR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2659),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2659),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 22,
                            CountryCode = "BS",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2660),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2661),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 23,
                            CountryCode = "BY",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2662),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2662),
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 24,
                            CountryCode = "BZ",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2663),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2664),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 25,
                            CountryCode = "CA",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2665),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2666),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 26,
                            CountryCode = "CH",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2667),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2667),
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 27,
                            CountryCode = "CI",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2668),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2669),
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 28,
                            CountryCode = "CL",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2670),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2670),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 29,
                            CountryCode = "CN",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2671),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2672),
                            Name = "China"
                        },
                        new
                        {
                            Id = 30,
                            CountryCode = "CO",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2673),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2673),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 31,
                            CountryCode = "CR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2675),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2675),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 32,
                            CountryCode = "CU",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2676),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2677),
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 33,
                            CountryCode = "CY",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2678),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2678),
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 34,
                            CountryCode = "CZ",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2679),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2680),
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 35,
                            CountryCode = "DO",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2681),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2681),
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 36,
                            CountryCode = "DK",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2682),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2683),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 37,
                            CountryCode = "DZ",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2684),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2684),
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 38,
                            CountryCode = "EC",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2685),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2686),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 39,
                            CountryCode = "EE",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2687),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2687),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 40,
                            CountryCode = "EG",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2688),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2689),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 41,
                            CountryCode = "ER",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2690),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2690),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 42,
                            CountryCode = "ES",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2692),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2692),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 43,
                            CountryCode = "ET",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2693),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2694),
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 44,
                            CountryCode = "FI",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2695),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2695),
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 45,
                            CountryCode = "FR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2696),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2697),
                            Name = "France"
                        },
                        new
                        {
                            Id = 46,
                            CountryCode = "GB",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2698),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2698),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 47,
                            CountryCode = "GE",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2699),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2700),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 48,
                            CountryCode = "GF",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2701),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2701),
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 49,
                            CountryCode = "GH",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2703),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2703),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 50,
                            CountryCode = "GL",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2704),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2705),
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 51,
                            CountryCode = "GP",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2706),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2706),
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 52,
                            CountryCode = "GR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2707),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2708),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 53,
                            CountryCode = "GT",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2776),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2777),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 54,
                            CountryCode = "GY",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2778),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2779),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 55,
                            CountryCode = "HN",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2780),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2780),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 56,
                            CountryCode = "HR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2782),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2782),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 57,
                            CountryCode = "HT",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2783),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2784),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 58,
                            CountryCode = "HU",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2785),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2785),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 59,
                            CountryCode = "ID",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2786),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2787),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 60,
                            CountryCode = "IE",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2788),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2788),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 61,
                            CountryCode = "IN",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2789),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2790),
                            Name = "India"
                        },
                        new
                        {
                            Id = 62,
                            CountryCode = "IR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2791),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2791),
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 63,
                            CountryCode = "IS",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2792),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2793),
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 64,
                            CountryCode = "IT",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2794),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2794),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 65,
                            CountryCode = "JM",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2796),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2796),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 66,
                            CountryCode = "JP",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2797),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2798),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 67,
                            CountryCode = "KE",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2799),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2799),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 68,
                            CountryCode = "KG",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2800),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2801),
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 69,
                            CountryCode = "KR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2802),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2802),
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 70,
                            CountryCode = "KW",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2803),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2804),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 71,
                            CountryCode = "KZ",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2805),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2805),
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 72,
                            CountryCode = "LU",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2807),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2807),
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 73,
                            CountryCode = "LT",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2808),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2809),
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 74,
                            CountryCode = "LV",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2810),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2810),
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 75,
                            CountryCode = "MA",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2811),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2812),
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 76,
                            CountryCode = "MC",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2813),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2813),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 77,
                            CountryCode = "MD",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2814),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2815),
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 78,
                            CountryCode = "MF",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2816),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2816),
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = 79,
                            CountryCode = "MG",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2817),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2818),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 80,
                            CountryCode = "MQ",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2819),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2819),
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 81,
                            CountryCode = "MT",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2821),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2821),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 82,
                            CountryCode = "MX",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2822),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2823),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 83,
                            CountryCode = "MY",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2824),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2824),
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 84,
                            CountryCode = "NG",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2825),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2826),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 85,
                            CountryCode = "NI",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2827),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2827),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 86,
                            CountryCode = "NL",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2828),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2829),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 87,
                            CountryCode = "NO",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2830),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2830),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 88,
                            CountryCode = "NZ",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2831),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2832),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 89,
                            CountryCode = "OM",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2833),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2833),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 90,
                            CountryCode = "PA",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2834),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2835),
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 91,
                            CountryCode = "PE",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2836),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2836),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 92,
                            CountryCode = "PL",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2837),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2838),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 93,
                            CountryCode = "PM",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2839),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2840),
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 94,
                            CountryCode = "PR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2841),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2841),
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 95,
                            CountryCode = "PT",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2842),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2843),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 96,
                            CountryCode = "PY",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2844),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2844),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 97,
                            CountryCode = "QA",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2845),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2846),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 98,
                            CountryCode = "RO",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2847),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2847),
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 99,
                            CountryCode = "RS",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2848),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2849),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 100,
                            CountryCode = "RU",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2850),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2850),
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 101,
                            CountryCode = "SA",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2851),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2852),
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 102,
                            CountryCode = "SE",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2853),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2853),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 103,
                            CountryCode = "SG",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2855),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2855),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 104,
                            CountryCode = "SI",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2856),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2857),
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 105,
                            CountryCode = "SK",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2858),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2858),
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 106,
                            CountryCode = "SN",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2859),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2860),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 107,
                            CountryCode = "SR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2861),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2861),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 108,
                            CountryCode = "SV",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2862),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2863),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 109,
                            CountryCode = "TR",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2864),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2864),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 110,
                            CountryCode = "TT",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2866),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2866),
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 111,
                            CountryCode = "UA",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2867),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2868),
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 112,
                            CountryCode = "US",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2869),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2869),
                            Name = "United States"
                        },
                        new
                        {
                            Id = 113,
                            CountryCode = "UY",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2870),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2871),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 114,
                            CountryCode = "VE",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2872),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2872),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 115,
                            CountryCode = "VI",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2873),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2874),
                            Name = "Virgin Islands"
                        },
                        new
                        {
                            Id = 116,
                            CountryCode = "VN",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2875),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2875),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 117,
                            CountryCode = "YE",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2876),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2877),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 118,
                            CountryCode = "ZA",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2878),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2878),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 119,
                            CountryCode = "ZM",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2880),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2880),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 120,
                            CountryCode = "ZW",
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2881),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(2882),
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("maERP.Domain.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEnrollment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("maERP.Domain.Models.CustomerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DefaultDeliveryAddress")
                        .HasColumnType("boolean");

                    b.Property<bool>("DefaultInvoiceAddress")
                        .HasColumnType("boolean");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseNr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAddress");
                });

            modelBuilder.Entity("maERP.Domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemoteOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SalesChannelId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("maERP.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Depth")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Msrp")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaxClassId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("TaxClassId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("maERP.Domain.Models.ProductSalesChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("RemoteProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SalesChannelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesChannelId");

                    b.ToTable("ProductSalesChannel");
                });

            modelBuilder.Entity("maERP.Domain.Models.ProductStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ProductStock");
                });

            modelBuilder.Entity("maERP.Domain.Models.SalesChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExportCustomers")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExportOrders")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExportProducts")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImportCustomers")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImportOrders")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImportProducts")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("SalesChannel");
                });

            modelBuilder.Entity("maERP.Domain.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("maERP.Domain.Models.ShippingProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShippingProvider");
                });

            modelBuilder.Entity("maERP.Domain.Models.ShippingProviderRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxHeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxLength")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxWidth")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ShippingProviderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShippingProviderId");

                    b.ToTable("ShippingProviderRate");
                });

            modelBuilder.Entity("maERP.Domain.Models.TaxClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TaxRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TaxClass");
                });

            modelBuilder.Entity("maERP.Domain.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Warehouse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(4115),
                            DateModified = new DateTime(2024, 5, 11, 18, 2, 49, 667, DateTimeKind.Utc).AddTicks(4115),
                            Name = "Warehouse 1"
                        });
                });

            modelBuilder.Entity("maERP.Domain.Models.CustomerAddress", b =>
                {
                    b.HasOne("maERP.Domain.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("maERP.Domain.Models.Customer", "Customer")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("maERP.Domain.Models.Order", b =>
                {
                    b.HasOne("maERP.Domain.Models.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("maERP.Domain.Models.Product", b =>
                {
                    b.HasOne("maERP.Domain.Models.TaxClass", "TaxClass")
                        .WithMany("Products")
                        .HasForeignKey("TaxClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxClass");
                });

            modelBuilder.Entity("maERP.Domain.Models.ProductSalesChannel", b =>
                {
                    b.HasOne("maERP.Domain.Models.Product", "Product")
                        .WithMany("ProductSalesChannel")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("maERP.Domain.Models.SalesChannel", "SalesChannel")
                        .WithMany()
                        .HasForeignKey("SalesChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesChannel");
                });

            modelBuilder.Entity("maERP.Domain.Models.ProductStock", b =>
                {
                    b.HasOne("maERP.Domain.Models.Product", null)
                        .WithMany("ProductStock")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("maERP.Domain.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("maERP.Domain.Models.SalesChannel", b =>
                {
                    b.HasOne("maERP.Domain.Models.Warehouse", "Warehouse")
                        .WithMany("SalesChannels")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("maERP.Domain.Models.ShippingProviderRate", b =>
                {
                    b.HasOne("maERP.Domain.Models.ShippingProvider", null)
                        .WithMany("ShippingRates")
                        .HasForeignKey("ShippingProviderId");
                });

            modelBuilder.Entity("maERP.Domain.Models.Customer", b =>
                {
                    b.Navigation("CustomerAddresses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("maERP.Domain.Models.Product", b =>
                {
                    b.Navigation("ProductSalesChannel");

                    b.Navigation("ProductStock");
                });

            modelBuilder.Entity("maERP.Domain.Models.ShippingProvider", b =>
                {
                    b.Navigation("ShippingRates");
                });

            modelBuilder.Entity("maERP.Domain.Models.TaxClass", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("maERP.Domain.Models.Warehouse", b =>
                {
                    b.Navigation("SalesChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
