name: maerp

services:
  maerp.server:
    image: ${DOCKER_REGISTRY-}maerp/server
    build:
      context: .
      dockerfile: src/maERP.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8443
      - DatabaseConfig__Provider=Sqlite
      - DatabaseConfig__ConnectionString=Data Source=/app/data/maerp.db
      - Logging__LogLevel__Default=Warning
    ports:
      - "8443:8443"
    volumes:
      - maerp-data:/app/data
    depends_on:
      - grafana-agent
    networks:
      - backend

  maerp.browser:
    image: ${DOCKER_REGISTRY-}maerp/web
    build:
      context: .
      dockerfile: src/maERP.UI.Browser/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8444
      - MAERP_SERVER_BASE_URL=http://localhost:8443
    ports:
      - "8444:8444"
    depends_on:
      - maerp.server
    networks:
      - backend


  grafana-agent:
    image: grafana/agent:latest
    entrypoint:
      - /bin/grafana-agent
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: grafana-agent
      REMOTE_WRITE_HOST: mimir:9009
      POSTGRES_HOST: postgres:5432
    ports:
      - "12345:12345"
    volumes:
      - ./grafana-agent/agent.yaml:/etc/agent-config/agent.yaml:ro
      - grafana-agent-wal:/tmp/agent/wal
    networks:
      - backend

volumes:
  maerp-data:
  grafana-agent-wal:

networks:
  backend:
    driver: bridge
