name: maERP.Server Publish

on:
  push:
    branches: [ main ]
    paths:
      - 'src/maERP.Server/**'
      - 'src/maERP.Core/**'
      - 'src/maERP.Domain/**'
      - 'src/maERP.Application/**'
      - 'src/maERP.Analytics/**'
      - 'src/maERP.Identity/**'
      - 'src/maERP.Infrastructure/**'
      - 'src/maERP.Persistence/**'
      - 'src/maERP.SalesChannels/**'
      - 'src/maERP.Persistence/**'
      - 'src/maERP.Persistence.MySQL/**'
      - 'src/maERP.Persistence.MSSQL/**'
      - 'src/maERP.Persistence.PostgreSQL/**'
      - 'src/maERP.Application.Persistence.IntegrationTests/**'
      - 'src/maERP.Application.UnitTests/**'
      - 'src/maERP.Server.Tests/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore maERP.Server.Tests
        run: dotnet restore tests/maERP.Server.Tests
      - name: Build maERP.Server.Tests
        run: dotnet build tests/maERP.Server.Tests --no-restore
      - name: Test maERP.Server.Tests
        run: dotnet test tests/maERP.Server.Tests --no-build --verbosity normal
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: maerp/server

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./src/maERP.Server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: maerp/server:latest
