using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace maERP.Server.Filters;

/// <summary>
/// Schema filter that ensures ASP.NET Core's ProblemDetails class
/// is properly documented with RFC 7807 schema definition.
/// </summary>
public class ProblemDetailsSchemaFilter : ISchemaFilter
{
    public void Apply(IOpenApiSchema schema, SchemaFilterContext context)
    {
        if (context.Type == typeof(ProblemDetails) && schema is OpenApiSchema openApiSchema)
        {
            // Override the default ProblemDetails schema with RFC 7807 compliant version
            openApiSchema.Properties ??= new Dictionary<string, IOpenApiSchema>();
            openApiSchema.Properties.Clear();
            openApiSchema.Properties.Add("type", new OpenApiSchema
            {
                Type = JsonSchemaType.String,
                Format = "uri",
                Description = "A URI reference that identifies the problem type. When dereferenced, it should provide human-readable documentation for the problem type."
            });

            openApiSchema.Properties.Add("title", new OpenApiSchema
            {
                Type = JsonSchemaType.String,
                Description = "A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem."
            });

            openApiSchema.Properties.Add("status", new OpenApiSchema
            {
                Type = JsonSchemaType.Integer,
                Format = "int32",
                Description = "The HTTP status code generated by the origin server for this occurrence of the problem."
            });

            openApiSchema.Properties.Add("detail", new OpenApiSchema
            {
                Type = JsonSchemaType.String,
                Description = "A human-readable explanation specific to this occurrence of the problem."
            });

            openApiSchema.Properties.Add("instance", new OpenApiSchema
            {
                Type = JsonSchemaType.String,
                Format = "uri",
                Description = "A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced."
            });

            openApiSchema.Properties.Add("traceId", new OpenApiSchema
            {
                Type = JsonSchemaType.String,
                Description = "The correlation ID for tracing this request across distributed systems."
            });

            // Allow additional properties for problem-specific extensions
            openApiSchema.AdditionalProperties = new OpenApiSchema
            {
                Type = JsonSchemaType.Object,
                Description = "Additional members can be used to carry problem-specific extension data."
            };

            openApiSchema.Example = new JsonObject
            {
                ["type"] = "https://tools.ietf.org/html/rfc9110#section-15.5.1",
                ["title"] = "Bad Request",
                ["status"] = 400,
                ["detail"] = "The 'name' field is required but was not provided in the request body.",
                ["instance"] = "/api/v1/products",
                ["traceId"] = "0HN7KBGV5C3QD:00000001",
                ["validationErrors"] = new JsonArray { "Name is required", "Price must be greater than 0" }
            };
        }
    }
}
